import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Providers from './Providers'
import { AuthProvider } from '@/contexts/AuthContext'

const ranade = localFont({
  src: [
    {
      path: '../../public/fonts/Ranade-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Ranade-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Ranade-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-ranade',
})

export const metadata: Metadata = {
  title: "TransportEase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={ranade.className}>
      <head>
        <script
          async
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
        />
      </head>
      <body>
        <AuthProvider>
          <Providers>{children}</Providers>
        </AuthProvider>
      </body>
    </html>
  )
}
